name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-test-and-report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: tests
        run: ./gradlew test

      - name: Publish tests report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            build/test-results/**/*.xml

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.9
        with:
          coverage_results_path: build/customJacocoReportDir/test/jacocoTestReport.xml
          coverage_report_name: Coverage

      - name: Mutation tests
        run: ./gradlew pitest